### PR TITLE
Opening hours

### PR DESCRIPTION
**Pull request by dan2811**
This adds the ability for superAdmins to CRUD opening hours for the school. These hours will be used to show opening and closing times on the diary view. 

To test the changes, you'll need to pull the branch, then run `bun db:push` (if you hit errors here you may need to wipe your db, run `bun db:push` then seed the data again), then `bun dev` and head to settings, click on opening hours and you should be able to CRUD opening hours if your user's role is a superAdmin. Any other role should not be able to create, update or delete opening hours. Every role should be able to view opening hours though.

### CODE REVIEW

**Review by Mariphy — COMMENTED** [review]
It seems like I can update everything and the functionality works here, but there are several  issues:
1. First of all, I think I can still update everything as an admin. 
2. When I'm trying to open the "Diary" section sometimes get a warning. Cannot update a component (`Router`) while rendering a different component (`Diary`). To locate the bad setState() call inside `Diary`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
3. When I edit the time by typing "04" or something else, I first get an error 'Unhandled Runtime Error
TRPCClientError: invalid input syntax for type time: "" '. Everything still works, I'm not sure if it affects anything at all.
4. And a very minor UX comment. When you choose time like 4pm to 8pm in the "Diary" section you need to scroll all the way to the bottom, do you think there is a point to hide morning hours when they are inactive?

Sorry if it is a lot. Let me know if you want a printscreen of the warning that I get or maybe have a call.

**Comment by dan2811** [comment]
> It seems like I can update everything and the functionality works here, but there are several issues:
> 
> 1. First of all, I think I can still update everything as an admin.
> 2. When I'm trying to open the "Diary" section sometimes get a warning. Cannot update a component (`Router`) while rendering a different component (`Diary`). To locate the bad setState() call inside `Diary`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
> 3. When I edit the time by typing "04" or something else, I first get an error 'Unhandled Runtime Error
>    TRPCClientError: invalid input syntax for type time: "" '. Everything still works, I'm not sure if it affects anything at all.
> 4. And a very minor UX comment. When you choose time like 4pm to 8pm in the "Diary" section you need to scroll all the way to the bottom, do you think there is a point to hide morning hours when they are inactive?
> 
> Sorry if it is a lot. Let me know if you want a printscreen of the warning that I get or maybe have a call.

Don't apologise, the more comments, the better! We will both learn faster and the code will get better quicker if we communicate lots! 😄 

1. Thanks, I will try and fix.
2. Yeah screenshot would be good, I don't get any errors at my end.
3. Interesting. On my end I'm unable to type anything other than a number in the field and when I type a number it works really nicely, like it doesn't let me type a type that doesn't exist, even if I try 99:99 it corrects to 23:59. I wonder if it's the browser handling this nicely, I'm using Chrome, what are running it in?
4. Excellent point! It's actually kind of already in there. But there has to be a lesson scheduled in for it to actually work. I think I'm ok with this, although it's not perfect, I think in reality it'll be good enough as it's extremely unlikely that there will be nothing booked in on a day. Screenshot for example:
Screenshot 2024-10-01 at 18 29 00

**Comment by Mariphy** [comment]
Screenshot 2024-10-01 101733
Screenshot 2024-10-01 101753

When I put "0" it gives an error, and as soon as I put the second number and it is "04" the error resolves. I'm not sure if it is a bad thing or if the error affects anything. I use Brave as my browser.

**Comment by dan2811** [comment]
> Screenshot 2024-10-01 101733 Screenshot 2024-10-01 101753
> 
> When I put "0" it gives an error, and as soon as I put the second number and it is "04" the error resolves. I'm not sure if it is a bad thing or if the error affects anything. I use Brave as my browser.

ok cool, I'm gonna put it down to a browser issue and the only requirement for this project is for it to work correctly on Chrome, so I'll leave it as it.

**Comment by Mariphy** [comment]
Hi, I double-checked that I now can't edit anything as admin. Although as a superAdmin, I toggled the Monday opening hours and got an error "TRPCClientError: duplicate key value violates unique constraint "openingHours_day_unique"".

**Pull request merged**
